services:
  db:
    build: ./Database/
    container_name: database
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - api_network

  server:
    build: ./API/
    container_name: server
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
